### ISSUE TITLE
US-1 Display

### ISSUE THREAD

**Issue by JuanSeBestia** [JuanSeBestia/calculator-angular-tdd#1]
1. Yo como usuario quiero ver el valor que tiene acutalmente la calculadora, para saber el resultado de mis opraciones

**Comment by jlcasasg** [comment]
I think this US miss some points, like which is the first input user will see? Like it is a '0', a message like 'introduce a number',  or just an empty input?

**Comment by JuanSeBestia** [comment]
The '0' value is okay
